"""Cambios en los modelos de transaction y planned_expense

Revision ID: 1a7204890f7d
Revises: fa03bb7cb4ac
Create Date: 2026-06-25 16:32:38.110250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a7204890f7d'
down_revision: Union[str, Sequence[str], None] = 'fa03bb7cb4ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_account_members_role'), table_name='group_account_members')
    op.create_index(op.f('ix_group_account_members_role'), 'group_account_members', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_account_members_role'), table_name='group_account_members')
    op.create_index(op.f('ix_group_account_members_role'), 'group_account_members', ['role'], unique=True)
    # ### end Alembic commands ###
