"""add account and transaction date to transactions

Revision ID: fa03bb7cb4ac
Revises: 72c9a41828ff
Create Date: 2026-06-23 06:20:40.997612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa03bb7cb4ac'
down_revision: Union[str, Sequence[str], None] = '72c9a41828ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planned_expenses', sa.Column('installments_paid', sa.Integer(), nullable=False, server_default=sa.text("0")))
    op.add_column('transactions', sa.Column('account_id', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('transaction_date', sa.DateTime(), nullable=False))
    op.alter_column('transactions', 'category_id', existing_type=sa.INTEGER(), nullable=False)
    op.create_foreign_key('fk_transactions_account_id_accounts', 'transactions', 'accounts', ['account_id'], ['id'])
    op.create_index('ix_transactions_account_id', 'transactions', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_account_id', table_name='transactions')
    op.drop_constraint('fk_transactions_account_id_accounts', 'transactions', type_='foreignkey')
    op.alter_column('transactions', 'category_id', existing_type=sa.INTEGER(), nullable=True)
    op.drop_column('transactions', 'transaction_date')
    op.drop_column('transactions', 'account_id')
    op.drop_column('planned_expenses', 'installments_paid')
    # ### end Alembic commands ###
