"""remover unique de groupaccount member role

Revision ID: 72c9a41828ff
Revises: ea0bf72c1e3d
Create Date: 2026-06-21 00:52:02.036100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c9a41828ff'
down_revision: Union[str, Sequence[str], None] = 'ea0bf72c1e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_account_members_role'), table_name='group_account_members')
    op.create_index(op.f('ix_group_account_members_role'), 'group_account_members', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_account_members_role'), table_name='group_account_members')
    op.create_index(op.f('ix_group_account_members_role'), 'group_account_members', ['role'], unique=True)
    # ### end Alembic commands ###
