"""agregar user id en transacciones, cambiar valores unicos en modelo de accounts y en user

Revision ID: 788cac11525d
Revises: c2db594b01d2
Create Date: 2026-06-26 16:41:26.194468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '788cac11525d'
down_revision: Union[str, Sequence[str], None] = 'c2db594b01d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if 'transactions_planned_expense_id_fkey' in {
        constraint['name']
        for constraint in inspector.get_foreign_keys('transactions')
    }:
        op.drop_constraint(op.f('transactions_planned_expense_id_fkey'), 'transactions', type_='foreignkey')

    if 'planned_expenses_legacy' in inspector.get_table_names():
        op.drop_index(op.f('ix_planned_expenses_id'), table_name='planned_expenses_legacy')
        op.drop_table('planned_expenses_legacy')

    if 'ix_accounts_name' in {index['name'] for index in inspector.get_indexes('accounts')}:
        op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)

    if 'user_id' not in {column['name'] for column in inspector.get_columns('transactions')}:
        op.add_column('transactions', sa.Column('user_id', sa.Integer(), nullable=True))

    if 'transactions_user_id_fkey' not in {
        constraint['name']
        for constraint in inspector.get_foreign_keys('transactions')
    }:
        op.create_foreign_key(op.f('transactions_user_id_fkey'), 'transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if 'transactions_user_id_fkey' in {
        constraint['name']
        for constraint in inspector.get_foreign_keys('transactions')
    }:
        op.drop_constraint(op.f('transactions_user_id_fkey'), 'transactions', type_='foreignkey')

    if 'user_id' in {column['name'] for column in inspector.get_columns('transactions')}:
        op.drop_column('transactions', 'user_id')

    if 'transactions_planned_expense_id_fkey' not in {
        constraint['name']
        for constraint in inspector.get_foreign_keys('transactions')
    }:
        op.create_foreign_key(op.f('transactions_planned_expense_id_fkey'), 'transactions', 'planned_expenses_legacy', ['planned_expense_id'], ['id'])

    if 'ix_accounts_name' in {index['name'] for index in inspector.get_indexes('accounts')}:
        op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=True)
    op.create_table('planned_expenses_legacy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=13, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('installment_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('installment_amount', sa.NUMERIC(precision=13, scale=2), autoincrement=False, nullable=False),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('creation_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('installments_paid', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('planned_expenses_account_id_fkey')),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], name=op.f('planned_expenses_status_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('planned_expenses_pkey'))
    )
    op.create_index(op.f('ix_planned_expenses_id'), 'planned_expenses_legacy', ['id'], unique=False)
    # ### end Alembic commands ###
